
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - data.nifi.site
  resources:
  - nifis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.nifi.site
  resources:
  - nifis/finalizers
  verbs:
  - update
- apiGroups:
  - data.nifi.site
  resources:
  - nifis/status
  verbs:
  - get
  - patch
  - update
